### ISSUE TITLE
to_yaml should produce valid Argo spec

### ISSUE THREAD

**Issue by process0** [argoproj-labs/argo-python-dsl#22]
Currently the `to_yaml` function will produce output that is not valid to be used with argo. Examples:

```
api_version: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generate_name: child-
  name: ''
```

Running `yaml.dump(sanitize_for_serialization(wf))` will produce valid spec.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: child-
  name: ''
```
